### PR TITLE
Responsiveness, Button Interactivity and File Structure

### PR DESCRIPTION
**Pull request by Dhavisco**
I edited the website so that it can be responsive. It can be viewed on different platforms and it maintains the page structure.
The button are now interactive. Users can easily identify that it is a button and it is interactive. It changes color when a user hovers and clicks on it.
I deleted some duplicate CSS file from the file structure.

### CODE REVIEW

**Comment by divyanshudhruv** [comment]
Can you open the pr in main branch ? Good luck

**Comment by divyanshudhruv** [comment]
@Dhavisco

**Comment by Dhavisco** [comment]
@divyanshudhruv kindly check the update

**Comment by Dhavisco** [comment]
@divyanshudhruv, any update on the pr?

**Comment by divyanshudhruv** [comment]
Hi, can I merge the pr after 6oct if you don't mind as currently I don't have the device to look into the code

**Comment by Dhavisco** [comment]
Alright. No problem

**Comment by divyanshudhruv** [comment]
Please resolve the conflicts. @Dhavisco

**Review by Dhavisco — COMMENTED** [review]
Resolved conflict of multiple css file

**Comment by Dhavisco** [comment]
@divyanshudhruv kindly check the update

**Comment by divyanshudhruv** [comment]
Still have some conflict

**Comment by divyanshudhruv** [comment]
Ok, sure

**Comment by divyanshudhruv** [comment]
Cam you publish the forked repo to gh pages ? Then I can easily see the changes.  Send me the link after you published it

**Comment by Dhavisco** [comment]
https://dhavisco.github.io/Minifolio/

**Comment by divyanshudhruv** [comment]
Cool but the home section is not responsive i.e. when the terminal type text is moving downward the space between home section and the about section is decreasing but it should remain same. Also the button is not perfectly styled. If you allow me to make some changes, it would be good. Good luck 


So can I make some changes ?

**Comment by Dhavisco** [comment]
Yes, you can.

**Comment by Dhavisco** [comment]
@divyanshudhruv please, any update?

**Comment by divyanshudhruv** [comment]
Added the hacktoberfest-accepted label, will merge soon

**Comment by Dhavisco** [comment]
Okay. Noted.

**Comment by divyanshudhruv** [comment]
@Dhavisco sorry for late merge

**Comment by Dhavisco** [comment]
It's fine. Thank you
It's nice to contribute to the project

**Comment by divyanshudhruv** [comment]
@Dhavisco did you get the Hacktoberfest Badge? See form your profile at hacktoberfest.com . If not then I'll merge

**Review by divyanshudhruv — APPROVED** [review]
Good job. This merge require some more changes. Else merging soon !

**Comment by Dhavisco** [comment]
> @Dhavisco did you get the Hacktoberfest Badge? See form your profile at hacktoberfest.com . If not then I'll merge

I did. Thank you.

**Comment by Dhavisco** [comment]
> @Dhavisco did you get the Hacktoberfest Badge? See form your profile at hacktoberfest.com . If not then I'll merge

I did. Thank you.

**Pull request closed without merging**
