### PR TITLE
Added a Hamburger Navigation Bar

### PR DESCRIPTION
**Pull request by jenyyy4**
I've streamlined the navigation experience with a sleek, modern design with the theme of the website intact.

### CODE REVIEW

**Comment by divyanshudhruv** [comment]
Thankyou for the contribution.

**Comment by jenyyy4** [comment]
@divyanshudhruv could you please merge my pr?

**Comment by divyanshudhruv** [comment]
> @divyanshudhruv could you please merge my pr?

@jenyyy4 yes sure, but can you resolve the files first?
**ALSO OPEN THE PR INTO `developement` BRANCH**

**Comment by divyanshudhruv** [comment]
added the `hacktoberfest-accepted` label. Enjoy ! 🎉

**Pull request merged**
