### PR TITLE
Logo of Minifolio

### PR DESCRIPTION
**Pull request by jenyyy4**

### CODE REVIEW

**Comment by divyanshudhruv** [comment]
@jenyyy4 please resolve the conflict

**Comment by jenyyy4** [comment]
@divyanshudhruv is it resolved?

**Comment by divyanshudhruv** [comment]
@jenyyy4 I mean, the navbar present in your code is not the navbar present in the portfolio (https://divyanshudhruv.github.io/Minifolio). So, I guess you need to check that or fork the repo once more via main branch and then add files with the directories. Sorry for the inconvenience.

### Portfolio ✅- 
image


### Your code ⛔- 
image

**Comment by jenyyy4** [comment]
@divyanshudhruv i made those changes before you added the navbar. you asked me to make a hamburger navbar, but you added a normal navbar now. what is that supposed to mean?

**Comment by divyanshudhruv** [comment]
@jenyyy4 don't worry about that, we will keep the hamburger navbar in the development branch because it needs some more styling. But after a few days we will add all the types of navbars and other sections to the portfolio (main branch) for the user to select and customize it to it's fullest. Don't worry about that. 🙃

**Comment by jenyyy4** [comment]
@divyanshudhruv but will my pr get merged though?

**Comment by divyanshudhruv** [comment]
@jenyyy4 merging it.

**Comment by divyanshudhruv** [comment]
looks good.

**Review by divyanshudhruv — APPROVED** [review]
Thank you for the contribution

**Pull request merged**
