### PR TITLE
added a navbar

### PR DESCRIPTION
**Pull request by jenyyy4**

### CODE REVIEW

**Comment by jenyyy4** [comment]
@divyanshudhruv resolved conflicts and reopened pr into development branch. please review this.

**Comment by jenyyy4** [comment]
@divyanshudhruv why was this closed with unmerged commits?

**Comment by divyanshudhruv** [comment]
@jenyyy4 can you please create a new PR. we are facing an issue with the branches

**Comment by divyanshudhruv** [comment]
@jenyyy4 in development branch

**Pull request closed without merging**
