### PR TITLE
Service section

### PR DESCRIPTION
**Pull request by arjungupta01**
Hyy i have added the service section 
i'm a newbie but i have given my 100% 
please merge it.

Thankyou

### CODE REVIEW

**Comment by divyanshudhruv** [comment]
Hey can you share the screenhshot @arjungupta01

**Comment by arjungupta01** [comment]
Screenshot 2023-10-04 115634

**Comment by arjungupta01** [comment]
Hey @divyanshudhruv 
I have shared the screenshot

**Comment by arjungupta01** [comment]
hey @divyanshudhruv please review and merge my pull request

**Pull request closed without merging**
