### PR TITLE
Added Back To Top Button

### LINKED ISSUE #7: Back to Top Button
Adding A Back to Top Button will make the portfolio more attractive Using CSS, and JavaScript.

Assign this issue to me under Hacktoberfest'23 I know that the show has not begun yet but I have already created one of my Portfolio websites using React, So I can make it as modern as you want to develop.

Here is the Screenshot of My portfolio Back to top Button
Screenshot 2023-09-27 012926

Assign this to me...

### PR DESCRIPTION
**Pull request by Kapileswar-Moharana**
Issue Title: Back to Top Button 
Issue Number: #7 

Close #7 

## Checklist:
- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy-to-understand README.md
- [x] The Back To Top Button works well on different devices.

## Description:

This pull request enhances the functionality of the "Back to Top" button in the HTML document by adding smooth scrolling behavior and dynamic visibility based on the user's scroll position. Here are the key changes:

## CSS:

Improved the styling of the button for better user experience.
Added a smooth transition effect on hover to make the button more interactive.
## JavaScript:

Added a click event listener to the "Back to Top" button.
When clicked, the page now smoothly scrolls back to the top.
The button dynamically appears when the user has scrolled down more than 200 pixels and hides when they are near the top of the page.
These enhancements provide a smoother and more user-friendly experience for navigating the webpage.

## Here is the Video Illustration of the Feature:

https://github.com/divyanshudhruv/Minifolio/assets/129049677/d6a3a532-fdca-40ac-a8b0-414ecfc9fada

### CODE REVIEW

**Comment by divyanshudhruv** [comment]
Cool but can you stlye the back to to button  as Know more button when hover as it is our theme i.e the background should be green and text as white only when hover

**Comment by Kapileswar-Moharana** [comment]
> stlye the back to to button as Know more button when hover as it is our theme i.e the background should be green and text as white only when hover

ok m doing

**Comment by divyanshudhruv** [comment]
Cool but instead of the black color for the icon use the shade of blueblack color. If possible

**Comment by divyanshudhruv** [comment]
Also try to lighter the shade of the the hover green color of button. You may use colorhex website for that.

**Comment by divyanshudhruv** [comment]
Alsonset the background color to f0f0f0

**Comment by Kapileswar-Moharana** [comment]
@divyanshudhruv All 3 tasks are done now check the changes here below are some Screenshots

Screenshot 2023-10-03 163016


Screenshot 2023-10-03 163054

**Comment by divyanshudhruv** [comment]
Cool just shift the button to a little more top and a little more left.

**Comment by Kapileswar-Moharana** [comment]
> Cool just shift the button to a little more top and a little more left.

I don't think it will look good because it is in perfect position, should i do these changes because i uploaded photo by croping screenshots make sure that

**Comment by Kapileswar-Moharana** [comment]
> > Cool just shift the button to a little more top and a little more left.
> 
> I don't think it will look good because it is in perfect position, should i do these changes because i uploaded photo by croping screenshots make sure that

**Comment by divyanshudhruv** [comment]
Ok then leave it I'll merge

**Comment by divyanshudhruv** [comment]
Can you publish the forked site to gh page? I may see that

**Comment by Kapileswar-Moharana** [comment]
> Ok then leave it I'll merge



> Can you publish the forked site to gh page? I may see that

Sorry not understand ?

**Comment by Kapileswar-Moharana** [comment]
> Can you publish the forked site to gh page? I may see that

@divyanshudhruv  https://github.com/Kapileswar-Moharana/Minifolio  is it ?

**Comment by divyanshudhruv** [comment]
I mean publish to gh pages, so that I can live preview

**Comment by Kapileswar-Moharana** [comment]
> I mean publish to gh pages, so that I can live preview

@divyanshudhruv  Check 
https://kapileswar-moharana.github.io/Minifolio/

**Comment by divyanshudhruv** [comment]
Also increase the zindex of the back to top button high as it is overlapping the footer.

**Comment by divyanshudhruv** [comment]
Screenshot_20231003_180654_Chrome

**Comment by Kapileswar-Moharana** [comment]
@divyanshudhruv already  updated Check it

**Comment by Kapileswar-Moharana** [comment]
@divyanshudhruv are there any other issues?

**Comment by Kapileswar-Moharana** [comment]
> Cool, will merge soon

@divyanshudhruv WHEN?

**Comment by divyanshudhruv** [comment]
@Kapileswar-Moharana merge. Congrats

**Comment by Kapileswar-Moharana** [comment]
> @Kapileswar-Moharana merge. Congrats

Thanks

**Pull request merged**
