### PR TITLE
chore: add 404 page

### PR DESCRIPTION
**Pull request by oyepriyansh**
https://github.com/divyanshudhruv/Minifolio/assets/83062406/e88d0db2-14b9-460e-b7e4-76c4675379c8

### CODE REVIEW

**Comment by oyepriyansh** [comment]
Fix #65

**Comment by divyanshudhruv** [comment]
cool but the background of button seems darker, you may set it to white

**Comment by oyepriyansh** [comment]
> cool but the background of button seems darker, you may set it to white

Fixed

**Review by divyanshudhruv — APPROVED** [review]
Good job !

**Pull request merged**
