### PR TITLE
Solve Fixes : #21 Add Terminal typing to role

### LINKED ISSUE #21: Add Dynamic text typing animation
## Adding Dynamic Typing text animation 
- a dynamic text animation on your website, featuring roles like 'Developer,' 'Blogger,' 'YouTuber,' and more,
-  we can use animation in the static 'Unknown Developer' or 'I'm a Developer element/area
- This makes the minifolio look cool

image
image

We can add in both or just one

### PR DESCRIPTION
**Pull request by mathanraj0601**
Fixes #21 
Added terminal typing to the role in minifolio

https://github.com/divyanshudhruv/Minifolio/assets/98396468/64feee44-3b44-42bb-8b5f-80c519a28b80

### CODE REVIEW

**Comment by divyanshudhruv** [comment]
Cool ! But you should try to change the green color to the grey color as that loons more cool.

**Comment by divyanshudhruv** [comment]
Also the back speed looks a bit fast... try to lower it down. Else good work

**Comment by mathanraj0601** [comment]
Sure divyan will update the Change asap
- Can i have back speed set to 20?
- Can you share the hex code for grey or simply i go for inbuilt grey in css?

**Comment by divyanshudhruv** [comment]
You may use the hex code from the css file present in the home section

**Comment by divyanshudhruv** [comment]
@mathanraj0601 Please resolve the conflict that occurred in index.html file and please share the video again after changing the color to grey

**Comment by mathanraj0601** [comment]
Sure divyan!

**Comment by mathanraj0601** [comment]
- [x] update text with grey color
- [x] resolved conflicts
- [x] increased typing back speed 
The final output:

https://github.com/divyanshudhruv/Minifolio/assets/98396468/8090798e-bf6f-4c61-ab09-069298a8c2a4

**Comment by divyanshudhruv** [comment]
- The color must set to color: #272341; instead of   color: #777; else good job, will merge it

**Comment by mathanraj0601** [comment]
I will change in a minute :)

**Comment by mathanraj0601** [comment]
- [x] update text color to #272341

**Comment by divyanshudhruv** [comment]
```suggestion
   <script> 
       // Custom the typed strings array based on your roles 
       var typed = new Typed("#role", { 
       strings: ["the Unknown Developer", "a UI/UX designer", "a Youtuber"], 
       typeSpeed: 210, 
       backSpeed: 40, 
       loop: true, 
       }); 
     </script>
```

**Comment by mathanraj0601** [comment]
Okay ! @divyanshudhruv 
I will change and commit.
is there any other change so I can make it in a single commit : )

**Comment by divyanshudhruv** [comment]
> Okay ! @divyanshudhruv I will change and commit. is there any other change so I can make it in a single commit : )

Yes let me see

**Comment by divyanshudhruv** [comment]
In index.html LINE 112 and LINE 122 remove the first `/` for the file location for all Javascript files

**Comment by mathanraj0601** [comment]
Anything else @divyanshudhruv

**Comment by divyanshudhruv** [comment]
> Anything else @divyanshudhruv

Hmm no

**Comment by divyanshudhruv** [comment]
> In index.html LINE 112 and LINE 122 remove the first `/` for the file location for all Javascript files. Also -
> 
> ```
>   <script> 
>       // Custom the typed strings array based on your roles 
>       var typed = new Typed("#role", { 
>       strings: ["the Unknown Developer", "a UI/UX Designer", "a Gamer"], 
>       typeSpeed: 210, 
>       backSpeed: 40, 
>       loop: true, 
>       }); 
>     </script>
> ```

Just copy this code

**Comment by mathanraj0601** [comment]
Thank you for your suggestions. Okay @divyanshudhruv  I will commit the changes : )

**Comment by mathanraj0601** [comment]
Feel free to tell any more suggestion : ) @divyanshudhruv

**Comment by divyanshudhruv** [comment]
> Feel free to tell any more suggestion : ) @divyanshudhruv

Ok, but it's all good

**Comment by mathanraj0601** [comment]
That's great

**Comment by divyanshudhruv** [comment]
At last - please change `d` in UI/UX designer to uppercase ie `UI/UX Designer` and create a new file for typing animation in javascript folder and link it to html, then I will be merging

**Comment by mathanraj0601** [comment]
Okay @divyanshudhruv

**Comment by divyanshudhruv** [comment]
Cool, thanx for your contribution, will merge soon

**Comment by mathanraj0601** [comment]
- [x] Capitalize D 
- [x] Added separate js file for animation.

**Comment by mathanraj0601** [comment]
> Cool, thanx for your contribution, will merge soon

Anytime !!

**Review by divyanshudhruv — APPROVED** [review]
Good Job !

**Comment by divyanshudhruv** [comment]
Congrats @mathanraj0601

**Comment by mathanraj0601** [comment]
Yeah : )

**Pull request merged**
