### PR TITLE
issue resolved #191 real time name change  and also added some styling

### LINKED ISSUE #191: Enabling real-time name update based on user input
@divyanshudhruv  sir the main issue is the contetnts are not chnaging at real time so i want it to be changed and also making the website more interactive towards end users

### PR DESCRIPTION
**Pull request by rahul-chakradhari**
1)real time name change 
https://github.com/user-attachments/assets/27b36de5-9e9e-4437-9652-94d61fddd6cb
Through this change we can get the real time name change feature which is mandatory 
2)some styling changes
https://github.com/user-attachments/assets/fe121fe7-9512-4cb1-a6a5-70aab6e5ae81
their is  need to change  since to make it  more effective towards end users.

### CODE REVIEW

**Comment by divyanshudhruv** [comment]
Hey i guess, if you make something like when a user clicks on "your name" an alert should pop up using javascript and that alert asks for the name, that would be better. And then the value of the input field should be transferred to that div, and new name would appear

**Comment by divyanshudhruv** [comment]
I'll merge it soon.

**Comment by divyanshudhruv** [comment]
> Hey i guess, if you make something like when a user clicks on "your name" an alert should pop up using javascript and that alert asks for the name, that would be better. And then the value of the input field should be transferred to that div, and new name would appear

@rahul-chakradhari have you made the required changes?

**Comment by rahul-chakradhari** [comment]
@divyanshudhruv sir you can check

**Comment by divyanshudhruv** [comment]
sure

**Review by divyanshudhruv — APPROVED** [review]
Merging

**Comment by rahul-chakradhari** [comment]
thanks @divyanshudhruv

**Comment by divyanshudhruv** [comment]
@rahul-chakradhari np, good luck

**Pull request merged**
