### PR TITLE
first commit

### PR DESCRIPTION
**Pull request by priyanshuxd9**
changed text and X logo

### CODE REVIEW

**Comment by divyanshudhruv** [comment]
screen shot please 😄

**Comment by priyanshuxd9** [comment]
> screen shot please 😄

I am sorry but I didn't intended to change your codebase, I just wanted to change things in my cloned repo and update the changes on github which is not happening for me and it is askng me to generate pull requests everytime I try to do it, can you help me anyhow?

**Comment by divyanshudhruv** [comment]
I guess you should fork the repo and instead of opening the pull request, you can go to the project settings and then go to "Github Pages" and then enable the page, by selecting the branch you want. I will guide you more

**Comment by divyanshudhruv** [comment]
I can see that the commit is present on your github repo. So it means that you have successfully applied the changes to your project. You are good to go. Just follow the steps to enable github pages and boom*.

**Comment by divyanshudhruv** [comment]
@priyanshuxd9

**Comment by priyanshuxd9** [comment]
alright will try the same and let you know, tqsm

**Pull request closed without merging**
