### PR TITLE
centered text and description for services cards

### PR DESCRIPTION
**Pull request by Pujan-khunt**
Centered the text and the description for the service cards.

Before:
image

After:
image

Kindly look into this PR @divyanshudhruv.

### CODE REVIEW

**Comment by divyanshudhruv** [comment]
@Pujan-khunt thank you, it looks good now. Also, what do you think, we should rename Web Development to Web Dev? Because by renaming that, the title and the paragraph would come at the same height for all the 3 cards.

**Comment by divyanshudhruv** [comment]
#158

**Comment by Pujan-khunt** [comment]
> @Pujan-khunt thank you, it looks good now. Also, what do you think, we should rename Web Development to Web Dev? Because by renaming that, the title and the paragraph would come at the same height for all the 3 cards.

I think that is a good suggestion and I can implement it. 

image

**Review by divyanshudhruv — APPROVED** [review]
Looks good

**Pull request merged**
