### PR TITLE
Implement the project section

### PR DESCRIPTION
**Pull request by AfubeAngel**
Your Repository Title With Link

# Short Description
This pull request adds a "Projects" section to the developer portfolio. The section includes a display of project cards with images, titles, descriptions, and links of each project.

# Points Added Or Removed
Added:
A new "Projects" section with a briefcase icon.
Three project cards with images, titles, descriptions, and links.

# Links To Issues
issue #110 

Files Changed
index.html: Added the section for displaying the project cards.
styles.css: Updated styles for the new "Projects" section, including layout, hover effects, and responsiveness.
assets folder: added an assets folder to store the images used in the profile section

### CODE REVIEW

**Comment by divyanshudhruv** [comment]
@AfubeAngel  can you re-fork the main branch and then reopen the pull request to the **`project-section-2`** branch ? thankyou, all the code looks good to me

**Comment by AfubeAngel** [comment]
@divyanshudhruv Alright. Would pull to ensure it is up to date with the merged PRs

**Comment by divyanshudhruv** [comment]
sure

**Comment by AfubeAngel** [comment]
@divyanshudhruv Done. So I reforked and pulled the update

**Pull request merged**
