### PR TITLE
Add Socials Sections

### PR DESCRIPTION
**Pull request by newtoallofthis123**
This commit adds a social div to the website template.

It uses the same ionicons and also adds helpful comments.

image

### CODE REVIEW

**Comment by newtoallofthis123** [comment]
This closes #18

**Comment by divyanshudhruv** [comment]
Hey, nice work.  But you can change the colors of the button to a flat color as it will look more nice.

**Comment by newtoallofthis123** [comment]
I will do that...but what do you mean by flat color? Can you please share an example?

**Comment by divyanshudhruv** [comment]
73924ce7401a7dd8e6c47bcfe94f1dd6

I mean color that seems soft to eyes

**Comment by newtoallofthis123** [comment]
Oh! Okay Done...will also help resolve a `style.css` conflict that happened :)

**Comment by divyanshudhruv** [comment]
Ok thank you, I hope you are able to resolve the style.css file conflict. Also please share the image after you changes the colors to a flat style by pinging me @divyanshudhruv

**Comment by newtoallofthis123** [comment]
Here are the colors @divyanshudhruv 
image

**Comment by divyanshudhruv** [comment]
Nice, but you can increase the padding of button just like the `Click me` button and instead of going column wise, go row wise. Also set the width to fit content.  **Or just copy the` button.css` code, do necessary changes to color only and then write the code for button.** I'll share you a pic soon about what we need for links

**Comment by newtoallofthis123** [comment]
I'll look into it

**Comment by divyanshudhruv** [comment]
I hope you didn't mind if I merge this request after 6 Oct as currently I do not have my device to look on the code.

**Comment by newtoallofthis123** [comment]
Oh that's alright! Take your time :)

**Comment by newtoallofthis123** [comment]
Something like this @divyanshudhruv 
image

**Comment by divyanshudhruv** [comment]
Yeah, just add more padding and increase border radius by 3-4 px. You may also add a small line explaining that **`These are some of my social media handels`** Just like this-

**Comment by newtoallofthis123** [comment]
done 

image

**Comment by divyanshudhruv** [comment]
Screenshot_20231001_115517_Chrome

Just like from LINE 51 to LINE 58 (it will add some apace after the title and the small line. It will Make the portolio look more minimal). Uncomment that do necessary changes and see the result.

**Comment by divyanshudhruv** [comment]
Actually I am on my tab, and I can merge you pr only after 6oct. Sorry for late merge

**Comment by newtoallofthis123** [comment]
Don't worry about it

**Comment by newtoallofthis123** [comment]
😄 Look good?
image

**Comment by newtoallofthis123** [comment]
So I can commit?

**Comment by divyanshudhruv** [comment]
Yeah ! Just a little more margin bottom to the small title. Then it would be fine

**Comment by newtoallofthis123** [comment]
Okay

**Comment by divyanshudhruv** [comment]
Is the button animation working?  If not,  copy the button code from the about section and put it here. 🙂

**Comment by newtoallofthis123** [comment]
Animations would not work because the background is declared by the user.

**Comment by divyanshudhruv** [comment]
May share a picture of final commit. Other than this, nice work. **### _Can I commit to your repo if I need some more changes ?_**

**Comment by newtoallofthis123** [comment]
cool :)

**Comment by divyanshudhruv** [comment]
> Animations would not work because the background is declared by the user.

Ok, Can I fix that ? By pushing code to your main branch ?

**Comment by newtoallofthis123** [comment]
sure!

**Comment by divyanshudhruv** [comment]
Can you send the pic of the final code(the social link section)

**Comment by newtoallofthis123** [comment]
okay

image

**Comment by divyanshudhruv** [comment]
And the website ?

**Comment by divyanshudhruv** [comment]
Any updates ?

**Comment by newtoallofthis123** [comment]
It is actually really weird to add button animations with the background color. It is trade off at this point. I mean, the animation we added to other buttons was a darkening effect...but there is no way we can do that dynamically in css unless we use sass.

What do you say?

**Comment by divyanshudhruv** [comment]
Please resolve the conflicts @newtoallofthis123

**Comment by newtoallofthis123** [comment]
> Please resolve the conflicts @newtoallofthis123 

Yeah I'll get to it

**Comment by newtoallofthis123** [comment]
> @newtoallofthis123 can you publish the forked repo to gh pages? Then I can easily see the changes. Also send me the link after u successfully published 

I can't really publish to gh pages since I don't own the repo....I'll see if i can get you a love preview

**Comment by divyanshudhruv** [comment]
Nono I mean publish your forked repo. That you can do I think

**Comment by newtoallofthis123** [comment]
Oh okay

**Comment by divyanshudhruv** [comment]
Ok

**Comment by Mukesh-ghildiyal** [comment]
if u don't  mind shall i raise my  new pr for this social sections,because i think its taking quite too much time

**Comment by divyanshudhruv** [comment]
@newtoallofthis123 yea, you can open a new PR

**Pull request closed without merging**
