### PR TITLE
Adding Services section

### PR DESCRIPTION
**Pull request by Dhaneshwarguiyan**
#51 Added a services section and made the theme to match with the main theme also added responsiveness to the service section

please do check the pull request and notify me if there are any changes to make.

Thank you.

### CODE REVIEW

**Comment by divyanshudhruv** [comment]
Hey can you share the screen shot @Dhaneshwarguiyan

**Comment by Dhaneshwarguiyan** [comment]
here is the screenshot

Screenshot from 2023-10-04 08-37-34

here is the link to preview video


[Screencast from 04-10-23 08:38:08 AM IST.webm](https://github.com/divyanshudhruv/Minifolio/assets/116065351/d645428f-c7f0-4cda-ae36-21b4e5eee3e0)
.com/divyanshudhruv/Minifolio/assets/116065351/e62f0e2c-18b2-4657-9f21-c4eca4576bec)

**Comment by Dhaneshwarguiyan** [comment]
Hello
In which branch do i need to open the pull request ?
I have opened a pull request at main.

**Comment by divyanshudhruv** [comment]
Main only

**Comment by Dhaneshwarguiyan** [comment]
Please can you merge it with hacktoberfest accept

**Comment by divyanshudhruv** [comment]
@Dhaneshwarguiyan conflict file are present, resolve the conflict

**Comment by Dhaneshwarguiyan** [comment]
I have resolved the conflicts

**Comment by divyanshudhruv** [comment]
Ok, will merge soon. Actually there are some bug in the site so I have to fix that too. But I will merge it before 14th Oct. Good luck @Dhaneshwarguiyan

**Comment by Dhaneshwarguiyan** [comment]
[tut.webm](https://github.com/divyanshudhruv/Minifolio/assets/116065351/9c090f49-8908-410c-9892-86cc40e01df0)

**Comment by Dhaneshwarguiyan** [comment]
@divyanshudhruv Please let me know if there are any changes to make

**Comment by divyanshudhruv** [comment]
@Dhaneshwarguiyan ok. I will merge soon

**Pull request closed without merging**
