### PR TITLE
Features Added

### PR DESCRIPTION
**Pull request by Znoy108x**
(1) Page load animations.
(2) Change the landing page colour theme and illustrations.
(3) Added good-looking background. 
(4) Change font family.

### CODE REVIEW

**Comment by divyanshudhruv** [comment]
All good, but see the reviews that I made. You might change something.

**Comment by divyanshudhruv** [comment]
@Znoy108x can you send the pic of the changes you made ? Currently I do not have my appropriate device to look...

**Comment by Znoy108x** [comment]
> @Znoy108x can you send the pic of the changes you made ? Currently I do not have my appropriate device to look...

Sorry, after pushing the code, I deleted the files 😅 (But you can check later on - I made changes in the landing page)

**Comment by divyanshudhruv** [comment]
Ok will review it after 6 Oct. I hope you didn't mind the late pull request merge

**Comment by Znoy108x** [comment]
> Ok will review it after 6 Oct. I hope you didn't mind the late pull request merge

ok

**Comment by divyanshudhruv** [comment]
Can you publish the forked repo to gh pages, and share me the link? So that I can see the codes and site

**Comment by Znoy108x** [comment]
> Can you publish the forked repo to gh pages, and share me the link? So that I can see the codes and site. Also send me the link to gh page.

ok

**Pull request closed without merging**
