### PR TITLE
Contact Us Section

### LINKED ISSUE #16: ✨ Add contact section
## 🫤 Description

<br>

> Adding contact section to the portfolio

<br>

## 📍 Use Case

<br>

> Visitors will have multiple ways to get in touch with us.

<br>

## 📦 Additional Information

<br>

> **`Backend:`** Backend for getting the contact inputs and outputs.

<br>

## ✋🏻 Upvotes

<br>

> If you support this feature request, add a 👍🏻.

<br>

## 🤔 To-Do

<br>

> If you have specific tasks or action items related to this feature request, list them here.

<br>

## 🌱 Contribute

<br>

> - [x] I want to contribute 

  <br>
  
## 📌 Related Issue

<br>

> #6

### PR DESCRIPTION
**Pull request by Kapileswar-Moharana**
Issue Title: Back to Top Button 
Issue Number: #16 

Close #16 

## Checklist:
- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy-to-understand README.md
- [x] The Contact Us works well on different devices.

## Description:

This pull request enhances the functionality of the "Contact Us" Section in the HTML document by adding smooth scrolling behavior and dynamic visibility based on the user's scroll position. Here are the key changes:

## CSS:

Improved the styling of the button for better user experience.
Added a smooth transition effect on hover to make the button more interactive.

## Here is the Video Illustration of the Feature:

https://github.com/divyanshudhruv/Minifolio/assets/129049677/64d70138-70f0-4f76-8fea-d2804cf6cfb6

Screenshot 2023-10-22 204237

### CODE REVIEW

**Comment by divyanshudhruv** [comment]
Added the label, will merge later. Good job

**Comment by Kapileswar-Moharana** [comment]
> Added the label, will merge later. Good job

@divyanshudhruv when ? Only 7 days left sir

.? App to kuchh bologee to agee krungaa naa ,  kitnee time lagegaa...

**Comment by Kapileswar-Moharana** [comment]
> Added the label, will merge later. Good job

@divyanshudhruv Ok

**Comment by divyanshudhruv** [comment]
Ok will merge tomorrow, positively.. @Kapileswar-Moharana

**Comment by Kapileswar-Moharana** [comment]
> Ok will merge tomorrow, positively.. @Kapileswar-Moharana

Ok

**Review by divyanshudhruv — APPROVED** [review]
Good Job. But the changes are only temporary. Will try to update this section

**Comment by divyanshudhruv** [comment]
@Kapileswar-Moharana did you got the hacktoberfest badge from hacktoberfest.com ? As I added the label 'hacktoberfest-accepted' to this pr. Please tell me. If not then I will merge. I am not merging as it requir some more text enhancement.

**Comment by Kapileswar-Moharana** [comment]
> @Kapileswar-Moharana did you got the hacktoberfest badge from hacktoberfest.com ? As I added the label 'hacktoberfest-accepted' to this pr. Please tell me. If not then I will merge. I am not merging as it requir some more text enhancement.

Tell me which section that you want to enhance

**Comment by Kapileswar-Moharana** [comment]
> @Kapileswar-Moharana did you got the hacktoberfest badge from hacktoberfest.com ? As I added the label 'hacktoberfest-accepted' to this pr. Please tell me. If not then I will merge. I am not merging as it requir some more text enhancement.

@divyanshudhruv Not yet Accepted If you merge It then it will be much more better ?

**Comment by Kapileswar-Moharana** [comment]
> @Kapileswar-Moharana did you got the hacktoberfest badge from hacktoberfest.com ? As I added the label 'hacktoberfest-accepted' to this pr. Please tell me. If not then I will merge. I am not merging as it requir some more text enhancement.

@divyanshudhruv Yes i understand , you can also later update these code or  write new coe on the basis sir...incluing these pull request i am also fixing some of the bugs .. in project section... PR , As i told you several times sir.. due to creting changes in main branch , i am unable to raise another Pull request , as it is not merged yet ... ok sir... that's why i am asking you to merged it , Also you can see the forked pages link of my project section then you can decide to meged it or update it latter though I am fixing some bugs related to Footer, Back to top button and About section... So Merged it sir Yoy can also update these code or may rewrite these code later..

**Comment by divyanshudhruv** [comment]
Sorry will merge tomorrow at 12 pm

**Comment by divyanshudhruv** [comment]
@Kapileswar-Moharana can u change the branch to development? Also change for the project pr...

**Comment by Kapileswar-Moharana** [comment]
> @Kapileswar-Moharana can u change the branch to development? Also change for the project pr...

@divyanshudhruv Yes I did it for Project Section You Can Check Also , Only i make the Changes for Contact Section In main Branch

**Comment by Kapileswar-Moharana** [comment]
> @Kapileswar-Moharana can u change the branch to development? Also change for the project pr...

Okay Then I will make another Branch For Contact Section, But the Prev Optimiswed Code is not there, but the recent Showing Some kind of bugs whenevr i synchronise the code it started showing error, so if i started updating then it will be based on that bug code also that i don't know after which commit it showing error, Though a lots of commit merged and reverted also some merged conflicts may occur, some code may also deleted.So what should i do now?

**Comment by divyanshudhruv** [comment]
@Kapileswar-Moharana I think you can save the code in local folder and then Fork my repo again. It would work.

**Comment by Kapileswar-Moharana** [comment]
> @Kapileswar-Moharana I think you can save the code in local folder and then Fork my repo again. It would work.

@divyanshudhruv ok As per Yor Concern let's try this again as, the same thing i have tried several times but the same thing the bug is not in my code sir.. okk wait let me try this again...

**Comment by Kapileswar-Moharana** [comment]
> @Kapileswar-Moharana I think you can save the code in local folder and then Fork my repo again. It would work.

@divyanshudhruv I did the same sir .. though again i delete the fork and again fork your main branch code and clone it to my local system but still there is some kind of bug and the page is not reponsive as well your github page code was the best one then after the bug is created , this much sure sir that this is not  created from my codes bcz **"Back to top button"** is there in your pages link... So Check it sir.. from which commit this error comes,, And ### Iam Raising PR from 2 differenet Branches fro Two Different Sections 
- Contact Section
- Project Section
## As per Your Concern ... 
## @divyanshudhruv And Please Accept the New PR as I Close the Pev Ones..Dt-29 , So Sir Merge it soon

**Pull request closed without merging**
