### PR TITLE
Added Contact Section

### LINKED ISSUE #16: ✨ Add contact section
## 🫤 Description

<br>

> Adding contact section to the portfolio

<br>

## 📍 Use Case

<br>

> Visitors will have multiple ways to get in touch with us.

<br>

## 📦 Additional Information

<br>

> **`Backend:`** Backend for getting the contact inputs and outputs.

<br>

## ✋🏻 Upvotes

<br>

> If you support this feature request, add a 👍🏻.

<br>

## 🤔 To-Do

<br>

> If you have specific tasks or action items related to this feature request, list them here.

<br>

## 🌱 Contribute

<br>

> - [x] I want to contribute 

  <br>
  
## 📌 Related Issue

<br>

> #6

### PR DESCRIPTION
**Pull request by Kapileswar-Moharana**
Issue Title: Contact Us 
Issue Number: #16 

Close #16 

## Checklist:
- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy-to-understand README.md
- [x] The Contact Us works well on different devices.

## Description:

This pull request enhances the functionality of the "Contact Us" Section in the HTML document by adding smooth scrolling behavior and dynamic visibility based on the user's scroll position. Here are the key changes:

## CSS:

Improved the styling of the button for better user experience.
Added a smooth transition effect on hover to make the button more interactive.

## Here is the Video Illustration of the Feature:

https://github.com/divyanshudhruv/Minifolio/assets/129049677/64d70138-70f0-4f76-8fea-d2804cf6cfb6

Screenshot 2023-10-22 204237

### CODE REVIEW

**Comment by Kapileswar-Moharana** [comment]
@divyanshudhruv Done Your Request Make it happen Now... Sir Soon

**Comment by divyanshudhruv** [comment]
Thnx

**Comment by Kapileswar-Moharana** [comment]
> Thnx

@divyanshudhruv Hnna to sir Merge Kab Hoga ?

**Comment by Kapileswar-Moharana** [comment]
@divyanshudhruv Aree Bhai Dikkat kyaa haii bata saktee hoo ? Alkk Mahinaa ho gaya sir Kal karungaa kall Karungaa karke....Atleast abb to kardoo... @divyanshudhruv ?

**Comment by divyanshudhruv** [comment]
@Kapileswar-Moharana I merged one of your pr. Please resolve the conflict fast.

**Comment by divyanshudhruv** [comment]
@Kapileswar-Moharana 
@Kapileswar-Moharana 
@Kapileswar-Moharana

**Comment by Kapileswar-Moharana** [comment]
> @Kapileswar-Moharana 
> @Kapileswar-Moharana 
> @Kapileswar-Moharana 

@divyanshudhruv ok

**Comment by divyanshudhruv** [comment]
Done @Kapileswar-Moharana

**Comment by Kapileswar-Moharana** [comment]
> Done @Kapileswar-Moharana

@divyanshudhruv Ok

**Pull request merged**
