### PR TITLE
Made button appear at new Line in Smartphone View

### PR DESCRIPTION
**Pull request by Sujal-2820**
**Title:** Move "Click Me" Button to New Line on Mobile Devices

**Overview:**
This pull request addresses a layout issue on mobile devices where the "Click Me" button was not displaying correctly. The button has been adjusted to move to the next line, ensuring a better user experience on smaller screens.

**Changes:**
- Added CSS rules for responsive design on mobile devices
- Modified the "btn-about" button styles to ensure it moves to the next line on screens with a width of 450 pixels or less

**Approach:**
I added a media query to the CSS that targets screens with a maximum width of 375 pixels. Within this media query, I adjusted the styles for the "btn-about" button to ensure it displays as a block-level element, causing it to move to the next line on smaller screens while keeping the text in its original position.

**Testing Instructions:**
1. Open the application on a mobile device or in a responsive mode with a screen width of 375 pixels or less.
2. Navigate to the section where the "Click Me" button is located.
3. Verify that the "Click Me" button now appears on a new line while the text remains in its original position.

**Checklist for Reviewers:**
- [x] Confirm that the button moves to the next line on mobile devices.
- [x] Ensure that the text positioning remains unchanged.
- [x] Verify that the changes do not affect the layout on larger screens.

### CODE REVIEW

**Comment by divyanshudhruv** [comment]
Cool, will review it

**Comment by divyanshudhruv** [comment]
Can you send a picture of the button on the mobile screen ? I do not have the device to look into the code at this time.

**Comment by Sujal-2820** [comment]
Sure @divyanshudhruv. Here are some snippets of the UI for Different dimensions of Smartphones:

**For iPhone 12 Pro:**
image


**For Samsung Galaxy S8**
image


**For Google Pixel**
image

**Comment by divyanshudhruv** [comment]
Nice, but you can increase the top margin of the button to some extent. Also you may try to adjust the button to right of the text and share a pic. Then we can select which one to keep,the bottom one or the right one.

**Comment by Sujal-2820** [comment]
Ok 👍
I'll make the necessary changes and get back to you..

**Comment by Sujal-2820** [comment]
Here are the Updated versions:

*1.  Increased Top Margin of Button*
space_Increase
<br><br>&nbsp;

*2. Button adjusted to the right of the Text with centrally aligned Words inside Button*
image

**Comment by divyanshudhruv** [comment]
Can you decrease the padding of button so that the text- click me ,appear on the same line ? Then send a pic here. Good work

**Comment by Sujal-2820** [comment]
Thanks for the appreciation 🙂
Please review this?

image

<br><br>
**NOTE:** As soon as increase the space between the text and the button by even a small px, the button moves to the next line and whole appearance becomes dull

**Comment by divyanshudhruv** [comment]
Oo, so what do you think, which one is better? Down button or right button ?

**Comment by Sujal-2820** [comment]
In my opinion the Down Button would be more desirable and soothing to have a look at. This is usually seen in most websites in smartphone view.

**Comment by divyanshudhruv** [comment]
> Here are the Updated versions:
> 
> *1.  Increased Top Margin of Button*
> space_Increase
> <br><br>&nbsp;
> 
> *2. Button adjusted to the right of the Text with centrally aligned Words inside Button*
> image
> 
> 

You mean this one ??

**Comment by Sujal-2820** [comment]
Yes sir!

**Comment by divyanshudhruv** [comment]
Ok can you publish you forked repo to gh pages? So that I can see the result ? I currently don't have the device to look into the code

**Comment by Sujal-2820** [comment]
Ok 👍. I'll notify you once the page is published

**Comment by divyanshudhruv** [comment]
Ok also send me the link to gh page

**Comment by Sujal-2820** [comment]
Please review it once
link to the page: https://sujal-2820.github.io/Minifolio/

**Comment by divyanshudhruv** [comment]
Screenshot_20231002_154108_Chrome

Hello, I think you should do something to media query as the width of this tablet is very much but still instead of the button coming to right it is coming down. The down button should only be applicable to mobiles with less width not tablets with more width. Please see to it

**Comment by Sujal-2820** [comment]
Thanks for the suggestion 💯
I looked upon the issue and solved it accordingly. 

Please review it and inform me about any changes needed: https://sujal-2820.github.io/Minifolio/

**Comment by divyanshudhruv** [comment]
Cool all food. Good job , @Sujal-2820

**Review by divyanshudhruv — APPROVED** [review]
Good job !

**Comment by divyanshudhruv** [comment]
Btw who is main collaborator ? @Sujal-2820 or @Sujal-12345

**Comment by Sujal-2820** [comment]
Actually @Sujal-2820 is the main account of mine. I have actually connected my github desktop to @Sujal-12345. 

But the contribution counts from @Sujal-2820 only 😅

I am glad you liked it. Thanks!

**Comment by divyanshudhruv** [comment]
Will merge it soon

**Comment by Sujal-2820** [comment]
Sure 👍
Thank you so much!!

**Comment by divyanshudhruv** [comment]
Congrats @Sujal-2820

**Comment by Sujal-2820** [comment]
Wooh!!🚀
Thanks @divyanshudhruv for your support

**Pull request merged**
