### PR TITLE
Added Achievement section Successfully

### PR DESCRIPTION
**Pull request by Prachirsh**
The Achievements Section of our website provides users with the opportunity to showcase their personal milestones and accomplishments in various fields. This interactive feature allows users to document their achievements by adding their own entries under different categories, promoting a sense of pride and motivation within the community.

### CODE REVIEW

**Comment by divyanshudhruv** [comment]
@Prachirsh can you attach a screenshot also of the section?

**Comment by Prachirsh** [comment]
@divyanshudhruv Please review my new commit.

**Review by divyanshudhruv — APPROVED** [review]
Looks good

**Comment by Prachirsh** [comment]
Kindly check and if anything else need to update let me know

**Pull request closed without merging**
