### PR TITLE
Education Timeline

### LINKED ISSUE #113: Adding a Education Section with timeline.
I can add a similar responsive timeline with animations for the education section. This is my work from some other project.
Screenshot 2024-10-06 105054

### PR DESCRIPTION
**Pull request by Riddhi050803**
I have added a timeline for school, college, and master's with title, year, and description.
-Added pop-up animations.
-Added responsiveness.

Screenshot 2024-10-08 171230
image
Screenshot 2024-10-08 171339

closes #113

### CODE REVIEW

**Comment by divyanshudhruv** [comment]
@Riddhi050803 can you set the background color of the logo Or the icons in the circle as white? Also change the font-style so that the font matches the overall theme. Good luck

**Comment by Riddhi050803** [comment]
Screenshot 2024-10-09 123315
I have changed the color of the icons and font style according to the theme. Is it fine now?

**Comment by divyanshudhruv** [comment]
@Riddhi050803 yep, can you also change the style of YEAR text also? Else it looks cool

**Comment by Riddhi050803** [comment]
image

**Comment by divyanshudhruv** [comment]
@Riddhi050803 sure, merging it

**Review by divyanshudhruv — APPROVED** [review]
It is awesome

**Pull request merged**
