### PR TITLE
Added Back to top button

### LINKED ISSUE #7: Back to Top Button
Adding A Back to Top Button will make the portfolio more attractive Using CSS, and JavaScript.

Assign this issue to me under Hacktoberfest'23 I know that the show has not begun yet but I have already created one of my Portfolio websites using React, So I can make it as modern as you want to develop.

Here is the Screenshot of My portfolio Back to top Button
Screenshot 2023-09-27 012926

Assign this to me...

### PR DESCRIPTION
**Pull request by Mdfarhan9304**
Fixes #7 issue. I have added back to top button after 200px down. When you click on it will take you back to top https://imagetolink.com/ib/71jPyD9RVv. Please accept this time. You already ignored my navbar pr

### CODE REVIEW

**Comment by divyanshudhruv** [comment]
Hi, please ask the assigned contributor of # , and if he allows you to make or, then I will merge

**Comment by divyanshudhruv** [comment]
The index.html file is missing. Add that please 😃

**Comment by Mdfarhan9304** [comment]
Index.html added @divyanshudhruv  now you can merge it.

**Comment by divyanshudhruv** [comment]
Ok

**Comment by Mdfarhan9304** [comment]
Add it now bro

**Comment by divyanshudhruv** [comment]
Wait bro, I'll merge after 6oct

**Comment by divyanshudhruv** [comment]
@Mdfarhan9304 I will merge this also. Good luck

**Comment by divyanshudhruv** [comment]
conflicts !!

**Pull request closed without merging**
