### PR TITLE
Footer Enhanced ( Copyright with Year added & Fully Responsive )

### PR DESCRIPTION
**Pull request by Vishal-1004**
Added a Copy Right text as follows:
Copyright @ 2023 All Rights Reserved | Template Developed With By <> Divyanshu Dhruv

***The year 2023 get dynamically updated, so their no need to update it again and again every year manually***

##
The design is made responsive. Proof is given below:
Screenshot (1386)
Screenshot (1388)

### CODE REVIEW

**Comment by divyanshudhruv** [comment]
Cool !

**Comment by divyanshudhruv** [comment]
U may also do changes in README.md in the footer section

**Comment by Vishal-1004** [comment]
Ok i will make the respective changes right away,
Can you clearly tell me what all things should i mention in the footer part
of readme.md file

**Comment by divyanshudhruv** [comment]
@Vishal-1004 Sorry, I sent it by mistake as there is nothing to change in the Readme.md . I will merge it soon.

**Comment by Vishal-1004** [comment]
😂 no issues, even I was kind of surprise when you asked me update the
Readme.md file,
Waiting for you to merge ✌

**Review by newtoallofthis123 — APPROVED** [review]
lgtm 🚀

**Review by divyanshudhruv — APPROVED** [review]
Good job.

**Pull request merged**
