### PR TITLE
experience section

### PR DESCRIPTION
**Pull request by ParvamShah1**
i ahve created an experience section as per the requirements .
image
Please tell me if any changes are required .
otherwise please proceed to merge my pr.
Thanks!
#148 resolved.

### CODE REVIEW

**Comment by divyanshudhruv** [comment]
#148

**Comment by ParvamShah1** [comment]
When will you merge it ?

**Comment by divyanshudhruv** [comment]
Soon,

**Comment by ParvamShah1** [comment]
Hi @divyanshudhruv,

I hope you're doing well! I just wanted to kindly follow up on my pull request #175 . If there are any changes or improvements you'd like me to make, please do let me know. I'd be happy to address them.

i can see some merge conflicts on my end is it some thing to look upon.

Thank you for your time and consideration, and I look forward to your feedback!

Best regards,

**Comment by ParvamShah1** [comment]
??

**Comment by divyanshudhruv** [comment]
I will merge it, don't worry

**Comment by divyanshudhruv** [comment]
@ParvamShah1 please resolve the file conflict as soon as possible. Sorry for late merging. I apologize

**Review by divyanshudhruv — APPROVED** [review]
Good job, merged

**Pull request merged**
